### PR TITLE
Build docker test environment.

### PR DESCRIPTION
**Pull request by estenrye**
In order to run this repo locally, I have started working on building a
set of docker files to build and deploy a local test environment independent
of the operating system the developer is using.

I am currently trying to get portero configured correctly.  Any advice?

### CODE REVIEW

**Comment by githagman** [comment]
Hey!  Thanks for the hard work!  Portero is deprecated and unused unfortunately.

We use Conserje and Hapier to to the volunteer hours, I haven't personally ever set up Portero.  However, these docker files are definitely very important steps for Conserje and Hapier.  I sent you a slack invite if you want to chat about how these files might integrate with those.

**Comment by estenrye** [comment]
Are you still using openERP, now odoo as your backend?
Are you still using version 7.0?

**Comment by githagman** [comment]
Yup on 7.0 still.  There's an install openerp script in a repo https://github.com/FreeGeekTwinCities/install-openerp/blob/master/install-openerp.py.  We're running Ubuntu servers (old usual) so typically through a .deb package.  Hapier is a min node app we leave on using the forever package and conserje is a static directory of html/css/js we serve with nginx.

**Comment by githagman** [comment]
@estenrye Hey mate, sorry for the slow follow up!  How's your java these days?  Wanted to give you a bit more context, we're standing up a new java-base rest-api to completely cut out this openerp integration.  That product is way overkill and the performance has never been there for our use cases.  Do you have any interest in digging into this issue?

I have that compose set up you made ported and running over on this project on the develop branch.  I didn't take the time to remove the openerp steps but the goal would be its completely not needed!  I added a few goals on that ticket.  I can provide some dummy data from the prod DB too.
https://github.com/FreeGeekTwinCities/volunteer-db-rest-api/issues/1

**Comment by estenrye** [comment]
My java sucks.  Much more proficient with .Net Core.  Sorry I missed this email, been kind of busy with classes starting up again.

 

Esten

**Pull request closed without merging**
